import { writeFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import { loadEnv } from 'vite';

// Integrations
import svelte from '@astrojs/svelte';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';

// Adapters
import vercelAdapter from '@astrojs/vercel';
import netlifyAdapter from '@astrojs/netlify';
import nodeAdapter from '@astrojs/node';
import cloudflareAdapter from '@astrojs/cloudflare';

// Pre-load .env so values are available in this config, before Vite
const fileEnv = loadEnv(process.env.NODE_ENV || 'development', process.cwd(), '');

// Read an env var, preferring shell over .env, with a final fallback
const unwrapEnvVar = (varName, fallbackValue) =>
  process.env[varName] ?? fileEnv[varName] ?? fallbackValue;

// Determine the deploy target (vercel, netlify, cloudflare, node)
const deployTarget = unwrapEnvVar('PLATFORM', 'node').toLowerCase();

// Determine the output mode (static or server). Mixed prerender supported in static mode
const output = unwrapEnvVar('OUTPUT', 'static');

// The FQDN of where the site is hosted (used for sitemaps & canonical URLs)
const site = unwrapEnvVar('SITE_URL', 'https://web-check.xyz');

// The base URL of the site (if serving from a subdirectory)
const base = unwrapEnvVar('BASE_URL', '/');
// Normalised with a trailing slash, for building asset URLs (e.g. in SCSS)
const baseWithSlash = base.endsWith('/') ? base : `${base}/`;

// Expose the base path to the SCSS module graph. Vite's `additionalData` does
// not reach @use/@forward'd partials (Sass module scoping), so we write a tiny
// generated partial that typography.scss and global.scss @use instead. This is
// regenerated on every Astro command, so it always matches the current BASE_URL.
writeFileSync(
  './src/styles/_env.scss',
  `// AUTO-GENERATED by astro.config.mjs — do not edit. Reflects BASE_URL.\n` +
    `$base-url: "${baseWithSlash}";\n`,
);

// Should run the app in boss-mode (requires extra configuration)
const isBossServer = unwrapEnvVar('BOSS_SERVER', false);

// Initialize Astro integrations
const integrations = [svelte(), react(), sitemap()];

// Set the appropriate adapter, based on the deploy target.
// 'static'/'github' build a fully pre-rendered site (e.g. for GitHub Pages),
// where there is no server runtime, so no adapter is used.
function getAdapter(target) {
  switch (target) {
    case 'vercel':
      return vercelAdapter();
    case 'netlify':
      return netlifyAdapter();
    case 'cloudflare':
      return cloudflareAdapter();
    case 'node':
      return nodeAdapter({ mode: 'middleware' });
    case 'static':
    case 'github':
      return undefined;
    default:
      throw new Error(`Unsupported deploy target: ${target}`);
  }
}
const adapter = getAdapter(deployTarget);

// Print build information to console
console.log(
  `\n\x1b[1m\x1b[35m Preparing to start build of Web Check.... \x1b[0m\n`,
  `\x1b[35m\x1b[2mCompiling for "${deployTarget}" using "${output}" mode, ` +
    `to deploy to "${site}" at "${base}"\x1b[0m\n`,
  `\x1b[2m\x1b[36m🛟 For documentation and support, visit the GitHub repo: ` +
    `https://github.com/uTogglin/web-check \x1b[0m\n`,
);

const redirects = {
  '/about': '/check/about',
};

// Skip the marketing homepage for self-hosted users
if (!isBossServer && isBossServer !== true) {
  redirects['/'] = '/check';
}

// Split the heavy client-side vendor libraries out of the single ~850 kB island
// bundle into their own chunks. This lets the browser download them in parallel
// and cache each independently across deploys, so a change to app code no longer
// busts the (large, stable) charting/mapping vendor cache. Pure build-time
// chunking — it changes nothing about what the app fetches or renders.
const manualChunks = (id) => {
  if (!id.includes('node_modules')) return undefined;
  // Charting (recharts + its bundled d3 via victory-vendor) — the single
  // largest dependency, only needed by the score/footprint cards.
  if (id.includes('recharts') || id.includes('victory-vendor')) return 'vendor-charts';
  // World-map rendering (react-simple-maps + geo/topology helpers).
  if (id.includes('react-simple-maps') || id.includes('d3-geo') || id.includes('topojson'))
    return 'vendor-maps';
  // Stable framework core — changes rarely, so keep it cached across app deploys.
  if (
    id.includes('react-dom') ||
    id.includes('react-router') ||
    id.includes('scheduler') ||
    id.includes('@emotion')
  )
    return 'vendor-react';
  return undefined;
};

// Export Astro configuration. The adapter is only included when one is needed
// (server/hybrid targets); fully-static builds omit it entirely.
export default defineConfig({
  output,
  // Always trailing-slashed so import.meta.env.BASE_URL concatenates cleanly
  // with asset paths (e.g. `${BASE_URL}favicon.svg`) across the codebase.
  base: baseWithSlash,
  integrations,
  site,
  ...(adapter ? { adapter } : {}),
  redirects,
  vite: { build: { rollupOptions: { output: { manualChunks } } } },
});
